apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validate-webhook-$RESOURCE
webhooks:
- name: validate.default.svc.cluster.local
  rules:
  - apiGroups:   ["$API"]
    apiVersions: ["$VERSION"]
    operations:  ["CREATE"]
    resources:   ["$RESOURCE"]
    scope:       "Namespaced"
  clientConfig:
    service:
      name: validate
      namespace: default
      path: "/validate/$RESOURCE"
    caBundle: "$CA_PEM_B64"
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 5